version: '3'

services:
  app:
    build: 
      context: app
      dockerfile: .docker/Dockerfile
    depends_on: 
      - mongo
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - MONGODB_URL=$MONGODB_URL
  frontend:
    build: 
      context: frontend
      dockerfile: .docker/Dockerfile
    depends_on:
      - app
    restart: always
    ports:
      - "8080:80"
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
